// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr_CcN3h-pein3SyxnnvSI_0bQSCWdtAc',
    appId: '1:7732674388:web:6b29376e651a202006d2c1',
    messagingSenderId: '7732674388',
    projectId: 'point-of-sales-66f61',
    authDomain: 'point-of-sales-66f61.firebaseapp.com',
    storageBucket: 'point-of-sales-66f61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2PopVle83rnl8v3JWxURxYT323T3RXLs',
    appId: '1:7732674388:android:4de4906db9e4dd7b06d2c1',
    messagingSenderId: '7732674388',
    projectId: 'point-of-sales-66f61',
    storageBucket: 'point-of-sales-66f61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAINmxeDOY73TDxGHLeZkNGHiy7xEmDkwE',
    appId: '1:7732674388:ios:075afd361a01520506d2c1',
    messagingSenderId: '7732674388',
    projectId: 'point-of-sales-66f61',
    storageBucket: 'point-of-sales-66f61.firebasestorage.app',
    iosBundleId: 'com.vidura.nexPosDesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAINmxeDOY73TDxGHLeZkNGHiy7xEmDkwE',
    appId: '1:7732674388:ios:075afd361a01520506d2c1',
    messagingSenderId: '7732674388',
    projectId: 'point-of-sales-66f61',
    storageBucket: 'point-of-sales-66f61.firebasestorage.app',
    iosBundleId: 'com.vidura.nexPosDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr_CcN3h-pein3SyxnnvSI_0bQSCWdtAc',
    appId: '1:7732674388:web:679fb76e36246b1e06d2c1',
    messagingSenderId: '7732674388',
    projectId: 'point-of-sales-66f61',
    authDomain: 'point-of-sales-66f61.firebaseapp.com',
    storageBucket: 'point-of-sales-66f61.firebasestorage.app',
  );
}
